# Generated by Django 3.1.2 on 2020-10-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(default=25),
        ),
    ]
