# Generated by Django 3.0.8 on 2020-10-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_hero_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
