# Generated by Django 3.1.1 on 2020-10-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_auto_20201016_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
