# Generated by Django 3.1.1 on 2020-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='score',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='age',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
