# Generated by Django 3.1.2 on 2020-10-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='learder',
            new_name='leader',
        ),
    ]
