# Generated by Django 3.0.8 on 2020-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_hero_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
