# Generated by Django 3.1.1 on 2020-10-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_hero_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
